set(GIT_REPO "https://github.com/vadz/libtiff.git")

function(vad_live)
  git_clone(TIFF)
  if(VAD_PREFER_STATIC OR VAD_TIFF_PREFER_STATIC)
    message(STATUS "Forcing libtiff static build.")
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  endif()
  add_subdirectory("${VAD_EXTERNAL_ROOT}/TIFF" "${VAD_EXTERNAL_ROOT}/TIFF/build_external_dep")
  add_library(TIFF INTERFACE)
  set_target_properties(TIFF PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${VAD_EXTERNAL_ROOT}/TIFF/libtiff")
  target_link_libraries(TIFF INTERFACE tiff ZLIB::ZLIB)
  add_library(TIFF::TIFF ALIAS TIFF)
endfunction()
