set(GIT_REPO "https://github.com/madler/zlib.git")

function(vad_live NAME)
  git_clone(${VAD_${NAME}_GIT_REPO} ZLIB)
  add_subdirectory("${VAD_EXTERNAL_ROOT}/ZLIB" "${VAD_EXTERNAL_ROOT}/ZLIB/build_external_dep")
  add_library(ZLIB INTERFACE)
  set_target_properties(ZLIB PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${VAD_EXTERNAL_ROOT}/ZLIB")
  if(ZLIB_BUILD_STATIC)
      set_target_properties(ZLIB PROPERTIES INTERFACE_LINK_LIBRARIES zlibstatic)
  else()
      set_target_properties(ZLIB PROPERTIES INTERFACE_LINK_LIBRARIES zlib)
  endif()
  add_library(ZLIB::ZLIB ALIAS ZLIB)
  set(ZLIB_FOUND TRUE CACHE INTERNAL "")
  message(STATUS "Setting ZLIB_INCLUDE_DIRS to '${VAD_EXTERNAL_ROOT}/ZLIB'.")
  set(ZLIB_INCLUDE_DIRS "${VAD_EXTERNAL_ROOT}/ZLIB" CACHE PATH "")
  message(STATUS "Setting ZLIB_LIBRARIES to the zlib target from the live dependency.")
  if(ZLIB_BUILD_STATIC)
    set(ZLIB_LIBRARIES zlibstatic CACHE FILEPATH "")
  else()
    set(ZLIB_LIBRARIES zlib CACHE FILEPATH "")
  endif()
endfunction()
