
if(VigraAddExecutableIncluded)
    return()
endif()

set(VigraAddExecutableDir "${CMAKE_CURRENT_LIST_DIR}")

function(vigra_add_executable NAME)
    add_executable(${NAME} ${ARGN})
    get_property(VAD_LIBRARY_DIR_LIST GLOBAL PROPERTY _VAD_LIBRARY_DIR_LIST)
    set(VAD_EXECUTABLE_PATH "$<TARGET_FILE:${NAME}>")
    if(WIN32)
        if(NOT VAD_LIBRARY_DIR_LIST STREQUAL "")
            set(VAD_LIBRARY_DIR_LIST "${VAD_LIBRARY_DIR_LIST};")
        endif()
        configure_file("${VigraAddExecutableDir}/run_exec.bat.in" "${CMAKE_CURRENT_BINARY_DIR}/run_${NAME}.bat.generate" @ONLY)
        file(GENERATE OUTPUT "$<TARGET_FILE_DIR:${NAME}>/run_${NAME}.bat" INPUT "${CMAKE_CURRENT_BINARY_DIR}/run_${NAME}.bat.generate")
    else()
        if(NOT VAD_LIBRARY_DIR_LIST STREQUAL "")
            string(REPLACE ";" ":" VAD_LIBRARY_DIR_LIST "${VAD_LIBRARY_DIR_LIST}")
            set(VAD_LIBRARY_DIR_LIST "${VAD_LIBRARY_DIR_LIST}:")
        endif()
        configure_file("${VigraAddExecutableDir}/run_exec.sh.in" "${CMAKE_CURRENT_BINARY_DIR}/run_${NAME}.sh.generate" @ONLY)
        file(GENERATE OUTPUT "$<TARGET_FILE_DIR:${NAME}>/run_${NAME}.sh" INPUT "${CMAKE_CURRENT_BINARY_DIR}/run_${NAME}.sh.generate")
    endif()
endfunction()
